import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/sections/navbar";
import { BgLines } from "@/components/bg-lines";
import { BgGradient } from "@/components/bg-gradient";
import { WppWidget } from "@/components/wppWidget";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased bg-silverTree-50`}>
        <Navbar />
        <WppWidget />

        <BgLines />
        <BgGradient />
        {children}
      </body>
    </html>
  );
}
